name: Render library update
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master

      - uses: r-lib/actions/setup-pandoc@master

      - name: Install dependencies
        run: |
          install.packages(c("csodata", "reshape2",
          "zoo", "xts", "dygraphs", "rio", "openxlsx", "parsedate",
          "janitor", "tidyverse", "readr", "forcats"))
        shell: Rscript {0}
      - name: Scrape the data
        run: Rscript mdd_scripts.R
        
      - name: Commit results
        run: |
          git add -A
          git commit -m 'New CSO Data' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
